### ISSUE TITLE
Icon's color is not changed well in Recycle View

### ISSUE THREAD

**Issue by jyyblue1987** [mathiazhagan01/DrawableColorChange#3]
when change icon in recycle view, some icon's color does not changed, after individual item is updated, color is changed.

when init recycle view, it display as follow
http://prntscr.com/ebl2ak

after 2th item is refreshed, icon color is changed.
http://prntscr.com/ebl2pl

**Comment by mathiazhagan01** [comment]
Thank you for opened this issue. I will fix ASAP.

**Comment by mathiazhagan01** [comment]
Please use setImageBitmap for now. I will fix the issue ASAP.

```
Drawable drawable = drawableColorChange.changeColorById(R.drawable.ic_favorite_black_48dp, R.color._1);
holder.icon.setImageBitmap(returnBitmap(drawable));
```

```
private Bitmap returnBitmap(Drawable drawable) {
        try {
            Bitmap bitmap;

            bitmap = Bitmap.createBitmap(drawable.getIntrinsicWidth(), drawable.getIntrinsicHeight(), Bitmap.Config.ARGB_8888);

            Canvas canvas = new Canvas(bitmap);
            drawable.setBounds(0, 0, canvas.getWidth(), canvas.getHeight());
            drawable.draw(canvas);
            return bitmap;
        } catch (OutOfMemoryError e) {
            // Handle the error
            return null;
        }
    }
```

**Comment by mathiazhagan01** [comment]
Fixed the issue. Please use setImageBitmap() and get the bitmap from getColorChangedBitmap().

```
drawableColorChange.changeColorById(R.drawable.ic_favorite_black_48dp, R.color._8);
holder.icon.setImageBitmap(drawableColorChange.getColorChangedBitmap());
```

**Comment by jyyblue1987** [comment]
Thank you for your response.

but it still have some issues. 

drawableColorChange.changeColorById(R.drawable.ic_favorite_black_48dp, R.color._8);
holder.icon.setImageBitmap(drawableColorChange.getColorChangedBitmap());

When I use above code, icon's color is changed in recycle view. 
but icon's edge is not still changed.

http://prntscr.com/ed2lhd

I want you to fix it.

Thanks&Regards.

**Comment by mathiazhagan01** [comment]
Please set ImageView to null and set the required bitmap.

```
holder.icon.setImageBitmap(null);
drawableColorChange.changeColorById(R.drawable.ic_favorite_black_48dp, R.color._8);
holder.icon.setImageBitmap(drawableColorChange.getColorChangedBitmap());
```

**Comment by jyyblue1987** [comment]
same issue.

**Comment by mathiazhagan01** [comment]
Can you please share your code?
